In [1]:
import numpy as np

In [2]:
type([1,2,3])

list

In [3]:
a=np.array([1,2,3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a=np.array([(1,2,3),(4,5,6)])

In [7]:
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
a.shape

(2, 3)

In [10]:
a.ndim

2

In [11]:
a.size

6

In [12]:
a.itemsize

4

In [13]:
a.size * a.itemsize

24

In [20]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [21]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a[1,1]

6

In [22]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [23]:
a.min()

1

In [24]:
a.max()

9

In [25]:
a.sum()

45

In [26]:
a.sum(axis=0)

array([12, 15, 18])

In [27]:
a.sum(axis=1)

array([ 6, 15, 24])

In [28]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [29]:
np.std(a)

2.581988897471611

In [30]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [31]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [32]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [33]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [34]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [35]:
x=np.array([(1,2,3,4),(5,6,7,8)])
y=np.array([(1,2,3,4),(5,6,7,8)])

In [37]:
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
print(x+y)

[[ 2  4  6  8]
 [10 12 14 16]]


In [40]:
print(x-y)

[[0 0 0 0]
 [0 0 0 0]]


In [41]:
print(x/y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
x.shape

(2, 4)

In [43]:
y.shape

(2, 4)

In [44]:
np.dot(x,y)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [45]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
b=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [46]:
a.shape

(3, 3)

In [47]:
b.shape

(3, 3)

In [48]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [50]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.full([3,3],50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])